"""changed game status in Game model to nullable

Revision ID: 1f0085b0939e
Revises: bdb1125c5790
Create Date: 2024-04-22 16:18:49.166084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f0085b0939e'
down_revision = 'bdb1125c5790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('game_status',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('game_status',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
