"""adds Game, Guess, User models

Revision ID: 89859644dbdd
Revises: 
Create Date: 2024-04-20 22:30:17.246234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89859644dbdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('game',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('lives', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('num_min', sa.Integer(), nullable=False),
    sa.Column('num_max', sa.Integer(), nullable=False),
    sa.Column('game_status', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('guess',
    sa.Column('guess_id', sa.Integer(), nullable=False),
    sa.Column('guess', sa.String(), nullable=False),
    sa.Column('correct_num', sa.Integer(), nullable=False),
    sa.Column('correct_loc', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('guess_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guess')
    op.drop_table('game')
    op.drop_table('user')
    # ### end Alembic commands ###
