"""Changed Guess model to allow nullable correct_num & correct_loc

Revision ID: bdb1125c5790
Revises: cffe200b99e8
Create Date: 2024-04-22 01:12:42.853474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdb1125c5790'
down_revision = 'cffe200b99e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guess', schema=None) as batch_op:
        batch_op.alter_column('correct_num',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('correct_loc',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guess', schema=None) as batch_op:
        batch_op.alter_column('correct_loc',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('correct_num',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
