"""Actually fixed guess model foreign key correctly

Revision ID: cffe200b99e8
Revises: 89859644dbdd
Create Date: 2024-04-21 15:00:24.032662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cffe200b99e8'
down_revision = '89859644dbdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guess', schema=None) as batch_op:
        batch_op.alter_column('game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('guess_game_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'game', ['game_id'], ['game_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guess', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('guess_game_id_fkey', 'user', ['game_id'], ['user_id'])
        batch_op.alter_column('game_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
